#!/bin/bash

echo "🚀 Deploying V-GNOME Advanced Intelligence Suite (Canvas) via API..."

WORKPAD_JSON='{"attributes":{"name":"V-GNOME: Advanced Intelligence Suite","width":1200,"height":800,"page":0,"pages":[{"id":"page-1","name":"Executive Overview","style":{"background":"#0F172A"},"elements":[{"id":"header-1","name":"header","type":"element","position":{"top":40,"left":40,"height":80,"width":800,"angle":0,"parent":null},"expression":"markdown \"# V-GNOME\\n### BIOMETRIC GLOBAL OVERVIEW\" | render css=\".canvasRenderEl h1 { color: #38BDF8; font-family: sans-serif; margin:0; } .canvasRenderEl h3 { color: #94A3B8; font-family: sans-serif; margin:0; }\""},{"id":"metric-1","name":"total_genomes","type":"element","position":{"top":150,"left":40,"height":160,"width":350,"angle":0,"parent":null},"expression":"essql query=\"SELECT count(*) as total FROM \\\"genomic_profiles\\\"\" | math \"total\" | metric label=\"Genomes Indexed\" | render containerStyle={containerStyle backgroundColor=\"#1E293B\" borderRadius=\"10px\" border=\"1px solid #334155\"} css=\".canvasRenderEl { color: #FFFFFF; }\""},{"id":"metric-2","name":"species_diversity","type":"element","position":{"top":150,"left":420,"height":160,"width":350,"angle":0,"parent":null},"expression":"essql query=\"SELECT count(DISTINCT cluster_id) as total FROM \\\"genomic_profiles\\\"\" | math \"total\" | metric label=\"Species Diversity\" | render containerStyle={containerStyle backgroundColor=\"#1E293B\" borderRadius=\"10px\" border=\"1px solid #334155\"} css=\".canvasRenderEl { color: #2DD4BF; }\""},{"id":"gauge-1","name":"avg_robustness","type":"element","position":{"top":350,"left":40,"height":400,"width":730,"angle":0,"parent":null},"expression":"essql query=\"SELECT avg(metrics.coding_robustness) as avg_r FROM \\\"genomic_profiles\\\"\" | math \"avg_r\" | progress shape=\"gauge\" max=0.5 label={formatnumber \"0.00\"} valueColor=\"#FACC15\" | render containerStyle={containerStyle backgroundColor=\"#1E293B\" borderRadius=\"10px\"} css=\".canvasRenderEl { color: #FFFFFF; }\""}]},{"id":"page-2","name":"Stability Audit","style":{"background":"#0F172A"},"elements":[{"id":"header-2","name":"header_stability","type":"element","position":{"top":40,"left":40,"height":80,"width":800,"angle":0,"parent":null},"expression":"markdown \"# STABILITY RANKING\\n### TOP EXTREMOPHILE CANDIDATES\" | render css=\".canvasRenderEl h1 { color: #FACC15; font-family: sans-serif; }\""},{"id":"table-stability","name":"stability_table","type":"element","position":{"top":150,"left":40,"height":600,"width":1120,"angle":0,"parent":null},"expression":"essql query=\"SELECT cluster_id, avg(metrics.gc_content) as gc, avg(metrics.coding_robustness) as robustness FROM \\\"genomic_profiles\\\" GROUP BY cluster_id ORDER BY robustness DESC LIMIT 15\" | table | render containerStyle={containerStyle backgroundColor=\"#1E293B\" borderRadius=\"10px\"} css=\".canvasRenderEl th { color: #FACC15; }\""}]}],"colors":["#38BDF8","#2DD4BF","#FACC15","#F472B6"],"assets":{},"variables":[],"groups":[],"css":""}}'

curl -X POST "http://localhost:5601/api/saved_objects/canvas-workpad/vgnome-intelligence-suite?overwrite=true" \
  -H "kbn-xsrf: true" \
  -H "Content-Type: application/json" \
  -d "$WORKPAD_JSON"

echo -e "\n\n✅ V-GNOME Suite Deployed!"
echo "Open it here: http://localhost:5601/app/canvas#/workpad/vgnome-intelligence-suite"
